version: "3.9"

services:
  web:
    build: .
    container_name: geo_scanner_web
    command: python manage.py runserver 0.0.0.0:3002
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy  # Wait for the db to be healthy
    environment:
      - DEBUG=True
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - geo_scanner_network

  db:
    image: postgres:14
    container_name: geo_scanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - geo_scanner_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  postgres_data:

networks:
  geo_scanner_network:
    driver: bridge
